---
title: "Good Cuck movements"
author: "MM"
date: "13/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cuckoos, echo=FALSE, warning=FALSE, message=FALSE}
########################

rm(list=ls())
library(maps)
library(sp)
library(maptools)
library(rgdal)
library(ggplot2)
library(ggmap)
library(ggrepel)

# using best of day data

dat<-read.csv("~/BTO/cuckoo_tracking/data/stopover_bestofday_spring_mig.csv", h=T)


dat2<-read.csv("~/BTO/cuckoo_tracking/data/processed_movebank_cuckoos_hybrid_filter_clean_stopovers.csv", h=T)


UK_travel<-read.csv("~/BTO/cuckoo_tracking/data/complete_cycles_UK_all_timing.csv", h=T)

UK_travel<-UK_travel[UK_travel$deployment_entry==FALSE,]

dat2$key<-paste(dat2$ptt, dat2$year.x)

dat3<-dat2[dat2$key %in% unique(paste(UK_travel$ptt, UK_travel$year)),]

dat3<-dat3[dat3$month<6,]

m1 <- get_map(location = c(5, 30), zoom=4)


for(i in unique(dat3$ptt))
{
  cols <- c("2012" = "red", "2013" = "blue", "2014" = "darkgreen", "2015" = "orange", "2016"= "cyan", "2017"= "black")

  
  g<-ggmap(m1)+
    geom_path(data=dat3[dat3$ptt==i,], aes(x=long, y=lat,
                                             colour=factor(year.x)))+
    geom_jitter(data=dat3[dat3$ptt==i,], aes(x=long, y=lat,
                colour=factor(year.x)), shape=1, width = 0.5, height= 0.5)+ggtitle(i)+
  
  geom_label_repel(data=dat[dat$ptt==i & dat$deployment_entry==FALSE,], aes(x=SO_median_long, y=SO_median_lat,
                colour=factor(year), label=substr(SO_start, 6,10)))+
  geom_label_repel(data=aggregate(year~breeding_entry, data=dat[dat$ptt==i & dat$deployment_entry==FALSE,], FUN=function(x){unique(x)})
                   , aes(x=-18, y=45,
                colour=factor(year), label=unique(substr(breeding_entry, 6,10)))) + scale_colour_manual(values = cols) 
  
  print(g)
 
}
  
  
```

