---
title: "West Africa cuckoo stopover rainfall patterns"
author: "Mark Miller"
date: "17 April 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE, message=F, warning=F}

#### work around for different laptop/desktop directories ####
#### !!!! RUN THIS !!!! ####
 if(Sys.info()['nodename']=="D9L5812"){
   setwd("C:/cuckoo_tracking")}else{
    setwd("N:/cuckoo_tracking")}

int_out<-read.csv('data/spring_rainfall_by_stopover.csv', h=T)

dat<-read.csv("data/stopover_bestofday_1daymin_recalc_spring_mig_summary_extras.csv", h=T)


### visualisastion  
  
library(ggplot2)

# order country factors by longitude

int_out$country<-factor(int_out$country, levels= c("Angola", "Democratic Republic of the Congo",
                                                   "Congo", "Gabon", "Central African Republic", 
                                                   "Cameroon", "Nigeria", "Togo", "Burkina Faso",
                                                   "Ghana", "Cote d'Ivoire", "Liberia", "Guinea", 
                                                   "Sierra Leone"))
for( i in 2012:2017)
  {
  int1<-int_out[int_out$year==i,]
  
  for(j in unique(int1$ptt))
      {
dtemp<-dat[dat$year==i & dat$ptt==j,]

p<-ggplot(data=int_out[int_out$ptt==j & int_out$year==i,], 
          aes(x=variable, y=value))+
geom_rect(aes(xmin=SO_startDOY, xmax=SO_endDOY, ymin=0, ymax=100), fill='grey')+
  geom_bar(stat='identity', colour='black')+
  geom_smooth(span=0.5, se=FALSE, linetype='dashed', col='red')+
  facet_wrap(~SO_startDOY+country)+theme_classic()+
  ylab('daily rainfall (mm)')+ xlab('Day of year')+
          ggtitle(paste("Year:",i,"   PTT:", j, "   Arr date:", dtemp$arrive_breeding, "   Mig speed:", round(dtemp$m4c_resid, 2)))

  print(p)
        
  }
}

```
